# Generated by Django 5.2 on 2025-04-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_device_created_at_device_device_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
