# Generated by Django 5.2 on 2025-04-15 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_alter_device_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='device',
            field=models.ForeignKey(db_column='device_id', on_delete=django.db.models.deletion.CASCADE, to='advertisement.device', to_field='device_id'),
        ),
    ]
