# Generated by Django 5.2 on 2025-04-15 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0004_alter_media_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='device',
            field=models.ForeignKey(db_column='device_id', on_delete=django.db.models.deletion.CASCADE, to='advertisement.device'),
        ),
    ]
