# Generated by Django 5.2 on 2025-04-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0006_alter_media_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='media_url',
        ),
        migrations.AddField(
            model_name='media',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='device_media/'),
        ),
    ]
