# Generated by Django 5.2 on 2025-04-21 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0007_remove_media_media_url_media_media_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branchName', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='branch_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='advertisement.branch'),
        ),
    ]
