# Generated by Django 5.2 on 2025-04-22 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0008_branch_device_branch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='animation_type',
            field=models.CharField(choices=[('fade in', 'Fade In'), ('zoom', 'Zoom'), ('rotate', 'Rotate'), ('slide', 'Slide')], max_length=10, null=True),
        ),
    ]
