# Generated by Django 5.2 on 2025-04-22 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0009_media_animation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='duration',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
