# Generated by Django 5.2 on 2025-04-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0011_media_isaudio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='isAudio',
            field=models.BooleanField(choices=[('0', 'False'), ('1', 'True')], default=True),
        ),
    ]
