# Generated by Django 5.2 on 2025-04-23 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0012_alter_media_isaudio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='branch_id',
            new_name='branch',
        ),
    ]
