# Generated by Django 5.2 on 2025-04-24 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0013_rename_branch_id_device_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='branch_name',
        ),
    ]
