# Generated by Django 5.2 on 2025-04-24 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0014_remove_device_branch_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='duration',
            field=models.IntegerField(null=True),
        ),
    ]
